### ISSUE TITLE
Computing influence on a CNN

### ISSUE THREAD

**Issue by groe-dennis** [kohpangwei/influence-release#12]
Hello,

I want to find the most influential training images for a CNN I created. Is there a way to accomplish this without reproducing my layer structure in your code and then retraining?

I was thinking about just copying the weights in the calculation process of the influence, but could not work out how to do this.

I would be very grateful if someone could get me a hint. Thanks in advance!

**Comment by Kunlun-Zhu** [comment]
Have you done it? Could you share how you do it?

**Comment by groe-dennis** [comment]
Sure. You will have to change the ig4_rbf_vs_inception.ipynb to include a CNN. They already included a CNN (all_CNN_c.py) which you can just use. In order to use your own CNN you have to change the inference function in all_CNN_c. The structure is just a basic tensorflow graph, you can look up the structure in your online tutorial of choice.

You may also have a look at my fork of the project in which I changed the code in order to fit my CNN.
