### ISSUE TITLE
Need help: what does `set_params_op` do?

### ISSUE THREAD

**Issue by tengerye** [kohpangwei/influence-release#13]
When I read the code at line [190](https://github.com/kohpangwei/influence-release/blob/master/influence/logisticRegressionWithLBFGS.py#L190) of file `logisticRegressionWithLBFGS.py` as follows:

`self.sess.run(self.set_params_op, feed_dict=params_feed_dict)`.

I am curious what exactly does it do? It does not return a value. If I commented it, the log message printed by `self.print_model_eval()` changed. Would someone please explain?

**Comment by tengerye** [comment]
My conclusion is the code assign the values of weights from logistic regression classifier to networks which will be used in `inference()` from the file `logisticRegressionWithLBFGS.py`

**Comment by Kunlun-Zhu** [comment]
Sounds true
