### ISSUE TITLE
Error in influence calculation for spam experiment

### ISSUE THREAD

**Issue by alewarne** [kohpangwei/influence-release#17]
In my opinion there is an error in the get_loo_influences() function that is used for the spam experiment:

https://github.com/kohpangwei/influence-release/blob/578bc458b4d7cc39ed7343b9b271a04b60c782b1/influence/binaryLogisticRegressionWithLBFGS.py#L134-L161

This piece of code calculates the influence "by hand" according to the formula from section 2.3 since gradients and hessian can be computed as closed form expressions in the case of logistic regression. The code uses the LU-decomposition of H to compute the quadratic-form-like term from the formula (to avoid calculation of H^-1) and everything is fine until the last line. Looking in the formula in section 2.3 we find that there are two sigma terms (one for x_test and one for x). In the case of this experiment, x_test == x and so the last line should be
`return sigma**2 * quad_x`
to account for this. For the saturated regions of the sigmoid function the difference is not so big but clearly, in between it can be quite big.

**Comment by kohpangwei** [comment]
You're right -- thanks for pointing it out!

**Comment by Airuibadi** [comment]
@kohpangwei  @alewarne Sorry to mention another question about spam experiment here. In spam experiment, the influence of a train point is I_up,loss(z_i, z_i), so what the exact mean of this value? Can I say that the higher influence means the higher probability of being a mislabel point？ Thank you :)
