### ISSUE TITLE
Upweighting a training point vs Perturbing a training input

### ISSUE THREAD

**Issue by HanGuo97** [kohpangwei/influence-release#18]
Hi, thanks again for this amazing work. I'm not sure this is the right place to ask this question, but I'm curious about the differences between these two approaches. Specifically, when should we use one approach vs. the other? Thanks in advance for the help!

**Comment by kohpangwei** [comment]
Hi Han,

Sorry for the late reply. These two approaches answer different questions: the first is when you want to see which training points are influential (i.e., what would happen if you removed them?) and the second is when you want to see how the model would respond if the training points were slightly different (e.g., if you were interested in what would happen if there was additive noise).

**Comment by HanGuo97** [comment]
Thanks for the explanation!
