### ISSUE TITLE
Mismatch between IHVP computation in code and paper?

### ISSUE THREAD

**Issue by Timsey** [kohpangwei/influence-release#19]
Hi, thanks for the great work! I've learned a lot from working to understand the paper.

I'm still having some trouble understanding how the current implementation mirrors the recursive computation of the IHVP as written in the paper. Specifically the following line (500 in influence/genericNeuralNet.py):

`cur_estimate = [a + (1-damping) * b - c/scale for (a,b,c) in zip(v, cur_estimate, hessian_vector_val)]`

Ignoring the damping and scaling term for now, this seems to implement something like:

`H_inv v <- v + H_inv v - H_est v`

Where v is the gradient, Hinv is the inverse Hessian estimate, and H_est is the estimate of the Hessian for a single data point (computed as an HVP with v). However, in the paper the algorithm says to compute:

`H_inv v <- v + (I - H_est) H_inv v = v + H_inv v - H_est H_inv v`

Which differs by a factor H_inv in the last term. Am I misunderstanding something?

**Comment by kohpangwei** [comment]
Hi! Glad the paper is helpful. The vector in `hessian_vector_val` refers to `cur_estimate`, so that should account for the missing `H_inv` term.
