### ISSUE TITLE
why does inverse_hvp / scale after the iteration in  get_inverse_hvp_lissa

### ISSUE THREAD

**Issue by cyyever** [kohpangwei/influence-release#20]
From #4  , I can understand why to use scale in HVP since the real loss function is scaled. But I don't know why to use scale at the end on line 507-510.

**Comment by kohpangwei** [comment]
In the loop, we scale the Hessian down by `scale`, which means that the estimate of the inverse Hessian-vector product will be scaled up by `scale`. The last division corrects for this scaling.
