### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by leo-liuzy** [kohpangwei/influence-release#21]
Thanks for the detailed documentation of your code!

I notice [here](https://github.com/kohpangwei/influence-release/blob/0f656964867da6ddcca16c14b3e4f0eef38a7472/influence/hessians.py#L23) that the correct hessian-vector product should be     1/2 (A + A.T) `v`

**Comment by kohpangwei** [comment]
Hmm, I don't think that's right, because the derivative of the quadratic form gives an extra factor of 2?

**Comment by leo-liuzy** [comment]
Yes, I think I blundered on math after checking the matrix cookbook. Sorry for the late reply!

**Comment by kohpangwei** [comment]
No problem at all, and thanks for the comment!
