### ISSUE TITLE
How much system memory is required in this source ?

### ISSUE THREAD

**Issue by bemoregt** [kohpangwei/influence-release#5]
Hi, @kohpangwei 

How much system memory is required in this source ?

I have 64GB Memory Machine, But this code used over 63GB nearly at data loading.

Is this normal? 

Thanksm in advance ~

**Comment by kohpangwei** [comment]
Hm, the Inception models need a lot of memory; are you trying to run those? You could try playing with the batch sizes to reduce the memory needed.

**Comment by bemoregt** [comment]
Hi, @kohpangwei 

I fixed it.
It's my fault.

Thanks.
