### ISSUE TITLE
How is the damping term determined?

### ISSUE THREAD

**Issue by donhk1011** [kohpangwei/influence-release#6]
Hi, 

@kohpangwei, How did you determine the damping term, 1e-2, in the 'train_minst.py'?

Is this general or specific to the CNN in the code?

I cannot find an explanation for that in the paper,

Thanks!

**Comment by kohpangwei** [comment]
Hi! It's specific to that CNN, and is chosen to be roughly the size of the most negative eigenvalue of the empirical Hessian (so that it becomes PSD).

**Comment by donhk1011** [comment]
Thanks!!
