### ISSUE TITLE
How to Computing Influence Function

### ISSUE THREAD

**Issue by jiamingzhang94** [kohpangwei/influence-release#8]
Hi,
I want to get the 
![image](https://user-images.githubusercontent.com/37396194/46902857-14751580-ceff-11e8-88a5-f8332b5e9787.png) of my model.
But I can't find the useful .py  for me...

Do you have any questions for me?
I have a trained model, train set and test set.
And I just want to get a pic likes this: (even without Euclidean distance)
![image](https://user-images.githubusercontent.com/37396194/46902912-f22fc780-ceff-11e8-9656-2d6dc710f098.png)

Thanks

**Comment by FateScript** [comment]
I drew a picture like this with ResNet-50 two month ago. You can use your model to extract features from train_set and test_set, and write a binary version for your model(you can see an Inception version in  influence/inceptionModel.py).Then please run scripts/run_rbf_comparison.py and use some code in scripts/fig4.ipynb, you may draw a picture like this. @z490938304

**Comment by PaulZhangIsing** [comment]
> I drew a picture like this with ResNet-50 two month ago. You can use your model to extract features from train_set and test_set, and write a binary version for your model(you can see an Inception version in influence/inceptionModel.py).Then please run scripts/run_rbf_comparison.py and use some code in scripts/fig4.ipynb, you may draw a picture like this. @z490938304

Have you ever tried to run it in a larger model, like ResNet and VGG16?
Seems it shall takes longer time.
If I customized the net ( like I may have done some reduction on the convolution layer, it runs even slower)

**Comment by Kunlun-Zhu** [comment]
> > I drew a picture like this with ResNet-50 two month ago. You can use your model to extract features from train_set and test_set, and write a binary version for your model(you can see an Inception version in influence/inceptionModel.py).Then please run scripts/run_rbf_comparison.py and use some code in scripts/fig4.ipynb, you may draw a picture like this. @z490938304
> 
> Have you ever tried to run it in a larger model, like ResNet and VGG16?
> Seems it shall takes longer time.
> If I customized the net ( like I may have done some reduction on the convolution layer, it runs even slower)

Seem true

**Comment by FateScript** [comment]
> > I drew a picture like this with ResNet-50 two month ago. You can use your model to extract features from train_set and test_set, and write a binary version for your model(you can see an Inception version in influence/inceptionModel.py).Then please run scripts/run_rbf_comparison.py and use some code in scripts/fig4.ipynb, you may draw a picture like this. @z490938304
> 
> Have you ever tried to run it in a larger model, like ResNet and VGG16?
> Seems it shall takes longer time.
> If I customized the net ( like I may have done some reduction on the convolution layer, it runs even slower)

I tried ResNet-50 but not VGG, it cost me about 1 days to draw such a pic. Actually the released code  could be more efficent, you may optimize it to get a shorter training time.

**Comment by HAoYifei996** [comment]
Hi, I'm trying to compute influence on VGG-16. I'm not sure about the `get_all_params()` part: should we get params for every layers in order for later computing or just some specific layers. I couldn't find the detailed code for extracting params of the Inception model used in the fig4 experiments except for this in `smooth_hing.py`:

```
def get_all_params(self):
        all_params = []
        for layer in ['softmax_linear']:
            # for var_name in ['weights', 'biases']:
            for var_name in ['weights']:
                temp_tensor = tf.get_default_graph().get_tensor_by_name("%s/%s:0" % (layer, var_name))            
                all_params.append(temp_tensor)      
        return all_params
```
